[workspace]
resolver = "2"
members = ["apps/api", "libs/auth", "libs/domain", "libs/ports"]


[workspace.package]
version = "0.1.0"
authors = ["nathaelb <pro.nathaelbonnal@gmail.com>"]
edition = "2024"
